### ISSUE TITLE
őŐűŰ - Hungarian characters

### ISSUE THREAD

**Issue by grafl** [theleagueof/league-gothic#25]
Hi,

is it possible to add these two characters to each weight and style?

Thank you.

**Comment by alerque** [comment]
I don't know when they got added, but the [1.600 release](https://github.com/theleagueof/league-gothic/releases/tag/1.600) has these characters all 4 font instances.

Given that there was no character support changes between 2014 and now, I'm confused about this issue since they should have been available in 1.560 as well. If there is still something the matter please comment here to let us know that support is incomplete, but as far as I can tell this is taken care of.
